var searchData=
[
  ['parameters',['parameters',['../interface_o_i_d_u_r_l_query_component.html#a5823699dbdfeb8fd940f6c5e6845893e',1,'OIDURLQueryComponent']]],
  ['performactionwithfreshtokens_3a',['performActionWithFreshTokens:',['../interface_o_i_d_auth_state.html#a0e7b2ea13d035b37cf48ddfd95065e9d',1,'OIDAuthState::performActionWithFreshTokens:(OIDAuthStateAction action)'],['../interface_o_i_d_auth_state.html#a0e7b2ea13d035b37cf48ddfd95065e9d',1,'OIDAuthState::performActionWithFreshTokens:(OIDAuthStateAction action)']]],
  ['performactionwithfreshtokens_3aadditionalrefreshparameters_3a',['performActionWithFreshTokens:additionalRefreshParameters:',['../interface_o_i_d_auth_state.html#a6ec4b90d600900d7d9179dbbb493bdd4',1,'OIDAuthState::performActionWithFreshTokens:additionalRefreshParameters:(OIDAuthStateAction action, [additionalRefreshParameters] nullable NSDictionary&lt; NSString *, NSString * &gt; *additionalParameters)'],['../interface_o_i_d_auth_state.html#a6ec4b90d600900d7d9179dbbb493bdd4',1,'OIDAuthState::performActionWithFreshTokens:additionalRefreshParameters:(OIDAuthStateAction action, [additionalRefreshParameters] nullable NSDictionary&lt; NSString *, NSString * &gt; *additionalParameters)']]],
  ['performactionwithfreshtokens_3aadditionalrefreshparameters_3adispatchqueue_3a',['performActionWithFreshTokens:additionalRefreshParameters:dispatchQueue:',['../interface_o_i_d_auth_state.html#a36f43d25573dcd2b7227205a6b53791b',1,'OIDAuthState::performActionWithFreshTokens:additionalRefreshParameters:dispatchQueue:(OIDAuthStateAction action, [additionalRefreshParameters] nullable NSDictionary&lt; NSString *, NSString * &gt; *additionalParameters, [dispatchQueue] dispatch_queue_t dispatchQueue)'],['../interface_o_i_d_auth_state.html#a36f43d25573dcd2b7227205a6b53791b',1,'OIDAuthState::performActionWithFreshTokens:additionalRefreshParameters:dispatchQueue:(OIDAuthStateAction action, [additionalRefreshParameters] nullable NSDictionary&lt; NSString *, NSString * &gt; *additionalParameters, [dispatchQueue] dispatch_queue_t dispatchQueue)']]],
  ['performregistrationrequest_3acompletion_3a',['performRegistrationRequest:completion:',['../interface_o_i_d_authorization_service.html#a60707ffeff1351fd6c30b94a2533ade2',1,'OIDAuthorizationService::performRegistrationRequest:completion:(OIDRegistrationRequest *request, [completion] OIDRegistrationCompletion completion)'],['../interface_o_i_d_authorization_service.html#a60707ffeff1351fd6c30b94a2533ade2',1,'OIDAuthorizationService::performRegistrationRequest:completion:(OIDRegistrationRequest *request, [completion] OIDRegistrationCompletion completion)']]],
  ['performtokenrequest_3acallback_3a',['performTokenRequest:callback:',['../interface_o_i_d_authorization_service.html#a74487299deeafa3fc5d302a7056aae80',1,'OIDAuthorizationService::performTokenRequest:callback:(OIDTokenRequest *request, [callback] OIDTokenCallback callback)'],['../interface_o_i_d_authorization_service.html#a74487299deeafa3fc5d302a7056aae80',1,'OIDAuthorizationService::performTokenRequest:callback:(OIDTokenRequest *request, [callback] OIDTokenCallback callback)']]],
  ['performtokenrequest_3aoriginalauthorizationresponse_3acallback_3a',['performTokenRequest:originalAuthorizationResponse:callback:',['../interface_o_i_d_authorization_service.html#a70983ded44634acc70cd347742f39af8',1,'OIDAuthorizationService::performTokenRequest:originalAuthorizationResponse:callback:(OIDTokenRequest *request, [originalAuthorizationResponse] OIDAuthorizationResponse *_Nullable authorizationResponse, [callback] OIDTokenCallback callback)'],['../interface_o_i_d_authorization_service.html#a70983ded44634acc70cd347742f39af8',1,'OIDAuthorizationService::performTokenRequest:originalAuthorizationResponse:callback:(OIDTokenRequest *request, [originalAuthorizationResponse] OIDAuthorizationResponse *_Nullable authorizationResponse, [callback] OIDTokenCallback callback)']]],
  ['pods_2dnxlauth_2dacknowledgements_2emarkdown',['Pods-NXLAuth-acknowledgements.markdown',['../_pods-_n_x_l_auth-acknowledgements_8markdown.html',1,'']]],
  ['pods_2dnxlauth_2ddummy_2em',['Pods-NXLAuth-dummy.m',['../_pods-_n_x_l_auth-dummy_8m.html',1,'']]],
  ['podsdummy_5fappauth',['PodsDummy_AppAuth',['../interface_pods_dummy___app_auth.html',1,'']]],
  ['podsdummy_5fpods_5fnxlauth',['PodsDummy_Pods_NXLAuth',['../interface_pods_dummy___pods___n_x_l_auth.html',1,'']]],
  ['postregistrationcallback',['PostRegistrationCallback',['../_n_x_l_app_auth_manager_8m.html#ab4f9b44b24ce7358e95589b84382ca00',1,'NXLAppAuthManager.m']]],
  ['presentauthorizationrequest_3aexternaluseragent_3acallback_3a',['presentAuthorizationRequest:externalUserAgent:callback:',['../interface_o_i_d_authorization_service.html#a9c086caf14e743acb61216aca74a272e',1,'OIDAuthorizationService::presentAuthorizationRequest:externalUserAgent:callback:(OIDAuthorizationRequest *request, [externalUserAgent] id&lt; OIDExternalUserAgent &gt; externalUserAgent, [callback] OIDAuthorizationCallback callback)'],['../interface_o_i_d_authorization_service.html#a9c086caf14e743acb61216aca74a272e',1,'OIDAuthorizationService::presentAuthorizationRequest:externalUserAgent:callback:(OIDAuthorizationRequest *request, [externalUserAgent] id&lt; OIDExternalUserAgent &gt; externalUserAgent, [callback] OIDAuthorizationCallback callback)']]],
  ['presentauthorizationrequest_3apresentingviewcontroller_3acallback_3a',['presentAuthorizationRequest:presentingViewController:callback:',['../category_o_i_d_authorization_service_07_i_o_s_08.html#a55fa456fe15dcfdd1e70b55dadeb773e',1,'OIDAuthorizationService(IOS)::presentAuthorizationRequest:presentingViewController:callback:(OIDAuthorizationRequest *request, [presentingViewController] UIViewController *presentingViewController, [callback] OIDAuthorizationCallback callback)'],['../category_o_i_d_authorization_service_07_i_o_s_08.html#a55fa456fe15dcfdd1e70b55dadeb773e',1,'OIDAuthorizationService(IOS)::presentAuthorizationRequest:presentingViewController:callback:(OIDAuthorizationRequest *request, [presentingViewController] UIViewController *presentingViewController, [callback] OIDAuthorizationCallback callback)'],['../interface_o_i_d_authorization_service.html#a55fa456fe15dcfdd1e70b55dadeb773e',1,'OIDAuthorizationService::presentAuthorizationRequest:presentingViewController:callback:(OIDAuthorizationRequest *request, [presentingViewController] UIViewController *presentingViewController, [callback] OIDAuthorizationCallback callback)'],['../interface_o_i_d_authorization_service.html#a55fa456fe15dcfdd1e70b55dadeb773e',1,'OIDAuthorizationService::presentAuthorizationRequest:presentingViewController:callback:(OIDAuthorizationRequest *request, [presentingViewController] UIViewController *presentingViewController, [callback] OIDAuthorizationCallback callback)']]],
  ['presentexternaluseragentrequest_3asession_3a',['presentExternalUserAgentRequest:session:',['../protocol_o_i_d_external_user_agent-p.html#a6a93e7b37031f33a6efa9a72fd20dd2f',1,'OIDExternalUserAgent-p::presentExternalUserAgentRequest:session:(id&lt; OIDExternalUserAgentRequest &gt; request, [session] id&lt; OIDExternalUserAgentSession &gt; session)'],['../protocol_o_i_d_external_user_agent-p.html#a6a93e7b37031f33a6efa9a72fd20dd2f',1,'OIDExternalUserAgent-p::presentExternalUserAgentRequest:session:(id&lt; OIDExternalUserAgentRequest &gt; request, [session] id&lt; OIDExternalUserAgentSession &gt; session)']]]
];
